# Generated by Django 5.2.5 on 2025-08-25 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_seq", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "gender",
                    models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=1),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("username", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=50, unique=True)),
                (
                    "last_login_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="PartnerClient",
            fields=[
                ("client_seq", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=150)),
                ("manager_name", models.CharField(max_length=100)),
                ("manager_email", models.EmailField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                ("contract_start", models.DateField()),
                ("contract_end", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "partner_client",
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_seq",
                        help_text="관리자로 승격된 회원의 일련번호",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.user",
                    ),
                ),
                ("admin_level", models.CharField(blank=True, max_length=50, null=True)),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "admin",
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                ("login_log_seq", models.AutoField(primary_key=True, serialize=False)),
                ("input_id", models.CharField(max_length=50)),
                (
                    "attempted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_success", models.BooleanField(default=False)),
                ("ip_address", models.CharField(max_length=45)),
                (
                    "fail_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "input_password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_seq",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "login_log",
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                ("news_seq", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "thumbnail_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("deleted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "전체"), (1, "내부발표"), (2, "외부발표")], default=0
                    ),
                ),
                ("excerpt", models.CharField(max_length=500)),
                ("badge", models.CharField(max_length=50)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_seq",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_posts",
                        to="accounts.admin",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        db_column="published_seq",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_posts",
                        to="accounts.admin",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_seq",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_posts",
                        to="accounts.admin",
                    ),
                ),
            ],
            options={
                "db_table": "news_post",
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                ("inquiry_seq", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_seq",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_inquiries",
                        to="accounts.admin",
                    ),
                ),
                (
                    "processor",
                    models.ForeignKey(
                        blank=True,
                        db_column="processor_seq",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_inquiries",
                        to="accounts.admin",
                    ),
                ),
            ],
            options={
                "db_table": "inquiry",
            },
        ),
    ]
