# Generated by Django 5.2.5 on 2025-09-04 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_seq",
                    models.AutoField(
                        db_column="USER_SEQ", primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_column="EMAIL", max_length=150, unique=True),
                ),
                (
                    "user_id",
                    models.CharField(db_column="USER_ID", max_length=50, unique=True),
                ),
                ("user_name", models.CharField(db_column="USER_NAME", max_length=100)),
                (
                    "password_hash",
                    models.CharField(db_column="PASSWORD_HASH", max_length=255),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성")],
                        db_column="GENDER",
                        max_length=1,
                    ),
                ),
                ("birth_date", models.DateField(db_column="BIRTH_DATE")),
                (
                    "joined_at",
                    models.DateTimeField(
                        db_column="JOINED_AT", default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, db_column="LAST_LOGIN_AT", null=True
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(blank=True, db_column="GRANTED_AT", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="CREATED_AT", default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_column="UPDATED_AT", null=True),
                ),
            ],
            options={
                "db_table": "T_USER",
            },
        ),
        migrations.CreateModel(
            name="UserLevel",
            fields=[
                (
                    "grade_code",
                    models.PositiveSmallIntegerField(
                        db_column="GRADE_CODE", primary_key=True, serialize=False
                    ),
                ),
                ("grade_name", models.CharField(db_column="GRADE_NAME", max_length=20)),
            ],
            options={
                "db_table": "T_USER_LEVEL",
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "login_log_seq",
                    models.AutoField(
                        db_column="LOGIN_LOG_SEQ", primary_key=True, serialize=False
                    ),
                ),
                ("input_id", models.CharField(db_column="INPUT_ID", max_length=50)),
                (
                    "attempted_at",
                    models.DateTimeField(
                        db_column="ATTEMPTED_AT", default=django.utils.timezone.now
                    ),
                ),
                ("is_success", models.BooleanField(db_column="IS_SUCCESS")),
                ("ip_address", models.CharField(db_column="IP_ADDRESS", max_length=45)),
                (
                    "user_agent",
                    models.TextField(blank=True, db_column="USER_AGENT", null=True),
                ),
                (
                    "input_password_hash",
                    models.CharField(
                        blank=True,
                        db_column="INPUT_PASSWORD_HASH",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="USER_SEQ",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="login_logs",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "T_LOGIN_LOG",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="grade_code",
            field=models.ForeignKey(
                db_column="GRADE_CODE",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.userlevel",
            ),
        ),
    ]
