# Generated by Django 5.2.5 on 2025-09-24 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_password_changed_at"),
    ]

    operations = []
