# Generated by Django 5.2.5 on 2025-09-28 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_seed_user_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="USER_SEQ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="login_logs",
                to="accounts.user",
            ),
        ),
    ]
