# Generated by Django 5.2.5 on 2025-09-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_loginlog_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, db_column="PASSWORD_CHANGED_AT", default=None, null=True
            ),
        ),
    ]
