# Generated by Django 5.2.5 on 2025-09-29 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsposthistory",
            name="deleted_reason",
        ),
    ]
