# Generated by Django 5.2.5 on 2025-09-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_remove_newsposthistory_deleted_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsposthistory",
            name="news_seq_snapshot",
            field=models.IntegerField(
                blank=True, db_column="NEWS_SEQ_SNAPSHOT", null=True
            ),
        ),
    ]
