# Generated by Django 5.2.5 on 2025-09-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_newsposthistory_news_seq_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsposthistory",
            name="title_snapshot",
            field=models.CharField(
                blank=True, db_column="TITLE_SNAPSHOT", max_length=200, null=True
            ),
        ),
    ]
