# Generated by Django 5.2.5 on 2025-09-29 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquiry",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="deleted_by",
        ),
    ]
