# Generated by Django 5.2.5 on 2025-09-04 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "inquiry_seq",
                    models.AutoField(
                        db_column="INQUIRY_SEQ", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="NAME", max_length=100)),
                ("email", models.EmailField(db_column="EMAIL", max_length=150)),
                ("title", models.CharField(db_column="TITLE", max_length=200)),
                ("message", models.TextField(db_column="MESSAGE")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_column="SUBMITTED_AT", default=django.utils.timezone.now
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, db_column="PROCESSED_AT", null=True
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(db_column="IS_PROCESSED", default=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="DELETED_AT", null=True),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="DELETED_SEQ",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deleted_inquiries",
                        to="accounts.user",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="PROCESSED_SEQ",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processed_inquiries",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "T_INQUIRY",
            },
        ),
    ]
