# Generated by Django 5.2.5 on 2025-09-04 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "news_seq",
                    models.AutoField(
                        db_column="NEWS_SEQ", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="TITLE", max_length=200)),
                ("content", models.TextField(db_column="CONTENT")),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True, db_column="THUMBNAIL_URL", max_length=255, null=True
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_column="PUBLISHED_AT", default=django.utils.timezone.now
                    ),
                ),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "전체"), (1, "내부발표"), (2, "외부발표")], default=0
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, db_column="IMAGE_URL", max_length=255, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_column="UPDATED_AT", null=True),
                ),
                ("excerpt", models.CharField(db_column="EXCERPT", max_length=500)),
                ("badge", models.CharField(db_column="BADGE", max_length=50)),
                (
                    "published_by",
                    models.ForeignKey(
                        db_column="PUBLISHED_SEQ",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_news_posts",
                        to="accounts.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="UPDATED_SEQ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_news_posts",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "T_NEWS_POST",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsPostHistory",
            fields=[
                (
                    "history_seq",
                    models.AutoField(
                        db_column="HISTORY_SEQ", primary_key=True, serialize=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(db_column="DELETED_AT")),
                (
                    "deleted_reason",
                    models.CharField(
                        blank=True,
                        db_column="DELETED_REASON",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        db_column="DELETED_SEQ",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_deletions",
                        to="accounts.user",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        blank=True,
                        db_column="NEWS_SEQ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="histories",
                        to="news.newspost",
                    ),
                ),
            ],
            options={
                "db_table": "T_NEWS_POST_HISTORY",
            },
        ),
    ]
